################## Project Specific Entries #######################
#
# These values override other definitions
#
# Project name

PROJECT=roach2_bsp
# module ID -> 32 bit hex (0xDEADCAFE == 3735931646)
BOARD_ID=3735931646
REV_MAJOR=0
REV_MINOR=0
RCS_UPTODATE=0
REV_RCS=0
# Pin Constraints
PCFILE=constraints/roach2_rev0.ucf
# Enter your source files here space seperated
#      Note: no spaces in filenames

SRC=./modules/toplevel/hdl/toplevel.v \
    ./modules/infrastructure/hdl/infrastructure.v \
    ./modules/clk_gen/hdl/clk_gen.v \
		./modules/knight_rider/hdl/knight_rider.v \
		./modules/knight_rider/hdl/pwm_sm.v \
		./modules/epb_infrastructure/hdl/epb_infrastructure.v \
		./modules/epb_wb_bridge_reg/hdl/epb_wb_bridge_reg.v \
		./modules/wbs_arbiter/hdl/timeout.v \
		./modules/wbs_arbiter/hdl/wbs_arbiter.v \
		./modules/sgmii_phy/hdl/sgmii_phy.v \
		./modules/sgmii_phy/hdl/sgmii_gtx.v \
		./modules/temac/hdl/emac_wrapper.v \
		./modules/temac/hdl/temac.v \
		./modules/gpio_controller/hdl/gpio_controller.v \
		./modules/sys_block/hdl/sys_block.v \
		./modules/qdr_controller_softcal/hdl/qdrc_infrastructure.v \
		./modules/qdr_controller_softcal/hdl/qdrc_phy_train.v \
		./modules/qdr_controller_softcal/hdl/qdrc_top.v \
		./modules/qdr_controller_softcal/hdl/qdr_controller_softcal.v \
		./modules/qdr_controller_softcal/hdl/qdrc_phy.v \
		./modules/qdr_controller_softcal/hdl/qdrc_phy_align.v \
		./modules/qdr_controller_softcal/hdl/qdr_cpu_attach.v

# Module name of toplevel entity
TOPLEVEL_MODULE=toplevel
# Logic Device Part Number
PARTNUM=6vsx475t-ff1759-1

# Verilog Include Directory
VINC=include

GEN_DIR=gen
NETLIST_DIR=netlist
