///////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version :  1.3
//  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard
//  /   /         Filename : gtx_wrapper.v
// /___/   /\     Timestamp :
// \   \  /  \
//  \___\/\___\
//
//
// Module GTX_WRAPPER (a GTX Wrapper)
// Generated by Xilinx Virtex-6 FPGA GTX Transceiver Wizard
// 
// 
// (c) Copyright 2009 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of,
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps


//***************************** Entity Declaration ****************************
(* CORE_GENERATION_INFO = "GTX_WRAPPER,v6_gtxwizard_v1_3,{protocol_file=xaui}" *) 
module GTX_WRAPPER #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTXRESET_SPEEDUP    = 0    // Set to 1 to speed up sim reset
)
(

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y0)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX0_LOOPBACK_IN,
    input   [1:0]   GTX0_RXPOWERDOWN_IN,
    input   [1:0]   GTX0_TXPOWERDOWN_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX0_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX0_RXCHARISK_OUT,
    output  [1:0]   GTX0_RXDISPERR_OUT,
    output  [1:0]   GTX0_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX0_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX0_RXCHBONDI_IN,
    input   [2:0]   GTX0_RXCHBONDLEVEL_IN,
    input           GTX0_RXCHBONDMASTER_IN,
    output  [3:0]   GTX0_RXCHBONDO_OUT,
    input           GTX0_RXCHBONDSLAVE_IN,
    input           GTX0_RXENCHANSYNC_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [2:0]   GTX0_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX0_RXBYTEISALIGNED_OUT,
    output          GTX0_RXBYTEREALIGN_OUT,
    output          GTX0_RXCOMMADET_OUT,
    input           GTX0_RXENMCOMMAALIGN_IN,
    input           GTX0_RXENPCOMMAALIGN_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX0_PRBSCNTRESET_IN,
    input   [2:0]   GTX0_RXENPRBSTST_IN,
    output          GTX0_RXPRBSERR_OUT,    
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX0_RXDATA_OUT,
    input           GTX0_RXRESET_IN,
    input           GTX0_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GTX0_RXCDRRESET_IN,
    output          GTX0_RXELECIDLE_OUT,
    input   [2:0]   GTX0_RXEQMIX_IN,
    input           GTX0_RXN_IN,
    input           GTX0_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GTX0_RXBUFRESET_IN,
    output  [2:0]   GTX0_RXBUFSTATUS_OUT,
    output          GTX0_RXCHANISALIGNED_OUT,
    output          GTX0_RXCHANREALIGN_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output  [1:0]   GTX0_RXLOSSOFSYNC_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX0_GTXRXRESET_IN,
    input           GTX0_MGTREFCLKRX_IN,
    input           GTX0_PLLRXRESET_IN,
    output          GTX0_RXPLLLKDET_OUT,
    output          GTX0_RXRESETDONE_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input   [7:0]   GTX0_DADDR_IN,
    input           GTX0_DCLK_IN,
    input           GTX0_DEN_IN,
    input   [15:0]  GTX0_DI_IN,
    output          GTX0_DRDY_OUT,
    output  [15:0]  GTX0_DRPDO_OUT,
    input           GTX0_DWE_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX0_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX0_TXDATA_IN,
    output          GTX0_TXOUTCLK_OUT,
    input           GTX0_TXRESET_IN,
    input           GTX0_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX0_TXDIFFCTRL_IN,
    output          GTX0_TXN_OUT,
    output          GTX0_TXP_OUT,
    input   [4:0]   GTX0_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX0_TXPREEMPHASIS_IN,
    //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
    input           GTX0_TXDLYALIGNDISABLE_IN,
    output  [7:0]   GTX0_TXDLYALIGNMONITOR_OUT,
    input           GTX0_TXDLYALIGNRESET_IN,
    input           GTX0_TXENPMAPHASEALIGN_IN,
    input           GTX0_TXPMASETPHASE_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX0_GTXTXRESET_IN,
    output          GTX0_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX0_TXENPRBSTST_IN,
    input           GTX0_TXPRBSFORCEERR_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input           GTX0_TXELECIDLE_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y1)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX1_LOOPBACK_IN,
    input   [1:0]   GTX1_RXPOWERDOWN_IN,
    input   [1:0]   GTX1_TXPOWERDOWN_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX1_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX1_RXCHARISK_OUT,
    output  [1:0]   GTX1_RXDISPERR_OUT,
    output  [1:0]   GTX1_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX1_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX1_RXCHBONDI_IN,
    input   [2:0]   GTX1_RXCHBONDLEVEL_IN,
    input           GTX1_RXCHBONDMASTER_IN,
    output  [3:0]   GTX1_RXCHBONDO_OUT,
    input           GTX1_RXCHBONDSLAVE_IN,
    input           GTX1_RXENCHANSYNC_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [2:0]   GTX1_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX1_RXBYTEISALIGNED_OUT,
    output          GTX1_RXBYTEREALIGN_OUT,
    output          GTX1_RXCOMMADET_OUT,
    input           GTX1_RXENMCOMMAALIGN_IN,
    input           GTX1_RXENPCOMMAALIGN_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX1_PRBSCNTRESET_IN,
    input   [2:0]   GTX1_RXENPRBSTST_IN,
    output          GTX1_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX1_RXDATA_OUT,
    input           GTX1_RXRESET_IN,
    input           GTX1_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GTX1_RXCDRRESET_IN,
    output          GTX1_RXELECIDLE_OUT,
    input   [2:0]   GTX1_RXEQMIX_IN,
    input           GTX1_RXN_IN,
    input           GTX1_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GTX1_RXBUFRESET_IN,
    output  [2:0]   GTX1_RXBUFSTATUS_OUT,
    output          GTX1_RXCHANISALIGNED_OUT,
    output          GTX1_RXCHANREALIGN_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output  [1:0]   GTX1_RXLOSSOFSYNC_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX1_GTXRXRESET_IN,
    input           GTX1_MGTREFCLKRX_IN,
    input           GTX1_PLLRXRESET_IN,
    output          GTX1_RXPLLLKDET_OUT,
    output          GTX1_RXRESETDONE_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input   [7:0]   GTX1_DADDR_IN,
    input           GTX1_DCLK_IN,
    input           GTX1_DEN_IN,
    input   [15:0]  GTX1_DI_IN,
    output          GTX1_DRDY_OUT,
    output  [15:0]  GTX1_DRPDO_OUT,
    input           GTX1_DWE_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX1_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX1_TXDATA_IN,
    output          GTX1_TXOUTCLK_OUT,
    input           GTX1_TXRESET_IN,
    input           GTX1_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX1_TXDIFFCTRL_IN,
    output          GTX1_TXN_OUT,
    output          GTX1_TXP_OUT,
    input   [4:0]   GTX1_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX1_TXPREEMPHASIS_IN,
    //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
    input           GTX1_TXDLYALIGNDISABLE_IN,
    output  [7:0]   GTX1_TXDLYALIGNMONITOR_OUT,
    input           GTX1_TXDLYALIGNRESET_IN,
    input           GTX1_TXENPMAPHASEALIGN_IN,
    input           GTX1_TXPMASETPHASE_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX1_GTXTXRESET_IN,
    output          GTX1_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX1_TXENPRBSTST_IN,
    input           GTX1_TXPRBSFORCEERR_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input           GTX1_TXELECIDLE_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX2  (X0Y2)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX2_LOOPBACK_IN,
    input   [1:0]   GTX2_RXPOWERDOWN_IN,
    input   [1:0]   GTX2_TXPOWERDOWN_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX2_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX2_RXCHARISK_OUT,
    output  [1:0]   GTX2_RXDISPERR_OUT,
    output  [1:0]   GTX2_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX2_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX2_RXCHBONDI_IN,
    input   [2:0]   GTX2_RXCHBONDLEVEL_IN,
    input           GTX2_RXCHBONDMASTER_IN,
    output  [3:0]   GTX2_RXCHBONDO_OUT,
    input           GTX2_RXCHBONDSLAVE_IN,
    input           GTX2_RXENCHANSYNC_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [2:0]   GTX2_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX2_RXBYTEISALIGNED_OUT,
    output          GTX2_RXBYTEREALIGN_OUT,
    output          GTX2_RXCOMMADET_OUT,
    input           GTX2_RXENMCOMMAALIGN_IN,
    input           GTX2_RXENPCOMMAALIGN_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX2_PRBSCNTRESET_IN,
    input   [2:0]   GTX2_RXENPRBSTST_IN,
    output          GTX2_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX2_RXDATA_OUT,
    input           GTX2_RXRESET_IN,
    input           GTX2_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GTX2_RXCDRRESET_IN,
    output          GTX2_RXELECIDLE_OUT,
    input   [2:0]   GTX2_RXEQMIX_IN,
    input           GTX2_RXN_IN,
    input           GTX2_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GTX2_RXBUFRESET_IN,
    output  [2:0]   GTX2_RXBUFSTATUS_OUT,
    output          GTX2_RXCHANISALIGNED_OUT,
    output          GTX2_RXCHANREALIGN_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output  [1:0]   GTX2_RXLOSSOFSYNC_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX2_GTXRXRESET_IN,
    input           GTX2_MGTREFCLKRX_IN,
    input           GTX2_PLLRXRESET_IN,
    output          GTX2_RXPLLLKDET_OUT,
    output          GTX2_RXRESETDONE_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input   [7:0]   GTX2_DADDR_IN,
    input           GTX2_DCLK_IN,
    input           GTX2_DEN_IN,
    input   [15:0]  GTX2_DI_IN,
    output          GTX2_DRDY_OUT,
    output  [15:0]  GTX2_DRPDO_OUT,
    input           GTX2_DWE_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX2_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX2_TXDATA_IN,
    output          GTX2_TXOUTCLK_OUT,
    input           GTX2_TXRESET_IN,
    input           GTX2_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX2_TXDIFFCTRL_IN,
    output          GTX2_TXN_OUT,
    output          GTX2_TXP_OUT,
    input   [4:0]   GTX2_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX2_TXPREEMPHASIS_IN,
    //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
    input           GTX2_TXDLYALIGNDISABLE_IN,
    output  [7:0]   GTX2_TXDLYALIGNMONITOR_OUT,
    input           GTX2_TXDLYALIGNRESET_IN,
    input           GTX2_TXENPMAPHASEALIGN_IN,
    input           GTX2_TXPMASETPHASE_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX2_GTXTXRESET_IN,
    output          GTX2_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX2_TXENPRBSTST_IN,
    input           GTX2_TXPRBSFORCEERR_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input           GTX2_TXELECIDLE_IN,


    
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX3  (X0Y3)

    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GTX3_LOOPBACK_IN,
    input   [1:0]   GTX3_RXPOWERDOWN_IN,
    input   [1:0]   GTX3_TXPOWERDOWN_IN,
    //--------------------- Receive Ports - 8b10b Decoder ----------------------
    output  [1:0]   GTX3_RXCHARISCOMMA_OUT,
    output  [1:0]   GTX3_RXCHARISK_OUT,
    output  [1:0]   GTX3_RXDISPERR_OUT,
    output  [1:0]   GTX3_RXNOTINTABLE_OUT,
    //----------------- Receive Ports - Channel Bonding Ports ------------------
    output          GTX3_RXCHANBONDSEQ_OUT,
    input   [3:0]   GTX3_RXCHBONDI_IN,
    input   [2:0]   GTX3_RXCHBONDLEVEL_IN,
    input           GTX3_RXCHBONDMASTER_IN,
    output  [3:0]   GTX3_RXCHBONDO_OUT,
    input           GTX3_RXCHBONDSLAVE_IN,
    input           GTX3_RXENCHANSYNC_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [2:0]   GTX3_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GTX3_RXBYTEISALIGNED_OUT,
    output          GTX3_RXBYTEREALIGN_OUT,
    output          GTX3_RXCOMMADET_OUT,
    input           GTX3_RXENMCOMMAALIGN_IN,
    input           GTX3_RXENPCOMMAALIGN_IN,
    //--------------------- Receive Ports - PRBS Detection ---------------------
    input           GTX3_PRBSCNTRESET_IN,
    input   [2:0]   GTX3_RXENPRBSTST_IN,
    output          GTX3_RXPRBSERR_OUT,
    //----------------- Receive Ports - RX Data Path interface -----------------
    output  [15:0]  GTX3_RXDATA_OUT,
    input           GTX3_RXRESET_IN,
    input           GTX3_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GTX3_RXCDRRESET_IN,
    output          GTX3_RXELECIDLE_OUT,
    input   [2:0]   GTX3_RXEQMIX_IN,
    input           GTX3_RXN_IN,
    input           GTX3_RXP_IN,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GTX3_RXBUFRESET_IN,
    output  [2:0]   GTX3_RXBUFSTATUS_OUT,
    output          GTX3_RXCHANISALIGNED_OUT,
    output          GTX3_RXCHANREALIGN_OUT,
    //------------- Receive Ports - RX Loss-of-sync State Machine --------------
    output  [1:0]   GTX3_RXLOSSOFSYNC_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    input           GTX3_GTXRXRESET_IN,
    input           GTX3_MGTREFCLKRX_IN,
    input           GTX3_PLLRXRESET_IN,
    output          GTX3_RXPLLLKDET_OUT,
    output          GTX3_RXRESETDONE_OUT,
    //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
    input   [7:0]   GTX3_DADDR_IN,
    input           GTX3_DCLK_IN,
    input           GTX3_DEN_IN,
    input   [15:0]  GTX3_DI_IN,
    output          GTX3_DRDY_OUT,
    output  [15:0]  GTX3_DRPDO_OUT,
    input           GTX3_DWE_IN,
    //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
    input   [1:0]   GTX3_TXCHARISK_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input   [15:0]  GTX3_TXDATA_IN,
    output          GTX3_TXOUTCLK_OUT,
    input           GTX3_TXRESET_IN,
    input           GTX3_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    input   [3:0]   GTX3_TXDIFFCTRL_IN,
    output          GTX3_TXN_OUT,
    output          GTX3_TXP_OUT,
    input   [4:0]   GTX3_TXPOSTEMPHASIS_IN,
    //------------- Transmit Ports - TX Driver and OOB signalling --------------
    input   [3:0]   GTX3_TXPREEMPHASIS_IN,
    //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
    input           GTX3_TXDLYALIGNDISABLE_IN,
    output  [7:0]   GTX3_TXDLYALIGNMONITOR_OUT,
    input           GTX3_TXDLYALIGNRESET_IN,
    input           GTX3_TXENPMAPHASEALIGN_IN,
    input           GTX3_TXPMASETPHASE_IN,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    input           GTX3_GTXTXRESET_IN,
    output          GTX3_TXRESETDONE_OUT,
    //------------------- Transmit Ports - TX PRBS Generator -------------------
    input   [2:0]   GTX3_TXENPRBSTST_IN,
    input           GTX3_TXPRBSFORCEERR_IN,
    //--------------- Transmit Ports - TX Ports for PCI Express ----------------
    input           GTX3_TXELECIDLE_IN,

    input           MGTREFCLK0_N,
    input           MGTREFCLK0_P,
    input           MGTREFCLK1_N,
    input           MGTREFCLK1_P,

    output          MGTREFCLK0,
    output          MGTREFCLK1
);
    
    wire refclk0;
    IBUFDS_GTXE1 IBUFDS_GTXE1_mgtrefclk0(
      .O     (refclk0),
      .ODIV2 (),
      .CEB   (1'b0),
      .I     (MGTREFCLK0_P),
      .IB    (MGTREFCLK0_N)
    );
    assign MGTREFCLK0 = refclk0;

    wire refclk1;
    IBUFDS_GTXE1 IBUFDS_GTXE1_mgtrefclk1(
      .O     (refclk1),
      .ODIV2 (),
      .CEB   (1'b0),
      .I     (MGTREFCLK1_P),
      .IB    (MGTREFCLK1_N)
    );
    assign MGTREFCLK1 = refclk1;

//***************************** Wire Declarations *****************************

    // ground and vcc signals
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [63:0]  tied_to_vcc_vec_i;

//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


//------------------------- GTX Instances  -------------------------------



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX0  (X0Y0)

    GTX_WRAPPER_GTX #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),

        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000000100)
    )
    gtx0_gtx_wrapper_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX0_LOOPBACK_IN),
        .RXPOWERDOWN_IN                 (GTX0_RXPOWERDOWN_IN),
        .TXPOWERDOWN_IN                 (GTX0_TXPOWERDOWN_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX0_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX0_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX0_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX0_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX0_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX0_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX0_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX0_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX0_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX0_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX0_RXENCHANSYNC_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GTX0_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX0_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GTX0_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GTX0_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX0_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX0_RXENPCOMMAALIGN_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX0_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX0_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX0_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX0_RXDATA_OUT),
        .RXRESET_IN                     (GTX0_RXRESET_IN),
        .RXUSRCLK2_IN                   (GTX0_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXCDRRESET_IN                  (GTX0_RXCDRRESET_IN),
        .RXELECIDLE_OUT                 (GTX0_RXELECIDLE_OUT),
        .RXEQMIX_IN                     (GTX0_RXEQMIX_IN),
        .RXN_IN                         (GTX0_RXN_IN),
        .RXP_IN                         (GTX0_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GTX0_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GTX0_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX0_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX0_RXCHANREALIGN_OUT),
        //------------- Receive Ports - RX Loss-of-sync State Machine --------------
        .RXLOSSOFSYNC_OUT               (GTX0_RXLOSSOFSYNC_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX0_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX0_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX0_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX0_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX0_RXRESETDONE_OUT),
        //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
        .DADDR_IN                       (GTX0_DADDR_IN),
        .DCLK_IN                        (GTX0_DCLK_IN),
        .DEN_IN                         (GTX0_DEN_IN),
        .DI_IN                          (GTX0_DI_IN),
        .DRDY_OUT                       (GTX0_DRDY_OUT),
        .DRPDO_OUT                      (GTX0_DRPDO_OUT),
        .DWE_IN                         (GTX0_DWE_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX0_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX0_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX0_TXOUTCLK_OUT),        
        .TXRESET_IN                     (GTX0_TXRESET_IN),
        .TXUSRCLK2_IN                   (GTX0_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX0_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX0_TXN_OUT),
        .TXP_OUT                        (GTX0_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX0_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX0_TXPREEMPHASIS_IN),
        //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
        .TXDLYALIGNDISABLE_IN           (GTX0_TXDLYALIGNDISABLE_IN),
        .TXDLYALIGNMONITOR_OUT          (GTX0_TXDLYALIGNMONITOR_OUT),
        .TXDLYALIGNRESET_IN             (GTX0_TXDLYALIGNRESET_IN),
        .TXENPMAPHASEALIGN_IN           (GTX0_TXENPMAPHASEALIGN_IN),
        .TXPMASETPHASE_IN               (GTX0_TXPMASETPHASE_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX0_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX0_MGTREFCLKRX_IN}),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .TXPLLLKDET_OUT                 (),
        .TXRESETDONE_OUT                (GTX0_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX0_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX0_TXPRBSFORCEERR_IN),
        //--------------- Transmit Ports - TX Ports for PCI Express ----------------
        .TXELECIDLE_IN                  (GTX0_TXELECIDLE_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX1  (X0Y1)

    GTX_WRAPPER_GTX #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),

        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000000100)
    )
    gtx1_gtx_wrapper_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX1_LOOPBACK_IN),
        .RXPOWERDOWN_IN                 (GTX1_RXPOWERDOWN_IN),
        .TXPOWERDOWN_IN                 (GTX1_TXPOWERDOWN_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX1_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX1_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX1_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX1_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX1_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX1_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX1_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX1_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX1_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX1_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX1_RXENCHANSYNC_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GTX1_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX1_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GTX1_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GTX1_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX1_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX1_RXENPCOMMAALIGN_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX1_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX1_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX1_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX1_RXDATA_OUT),
        .RXRESET_IN                     (GTX1_RXRESET_IN),
        .RXUSRCLK2_IN                   (GTX1_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXCDRRESET_IN                  (GTX1_RXCDRRESET_IN),
        .RXELECIDLE_OUT                 (GTX1_RXELECIDLE_OUT),
        .RXEQMIX_IN                     (GTX1_RXEQMIX_IN),
        .RXN_IN                         (GTX1_RXN_IN),
        .RXP_IN                         (GTX1_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GTX1_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GTX1_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX1_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX1_RXCHANREALIGN_OUT),
        //------------- Receive Ports - RX Loss-of-sync State Machine --------------
        .RXLOSSOFSYNC_OUT               (GTX1_RXLOSSOFSYNC_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX1_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX1_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX1_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX1_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX1_RXRESETDONE_OUT),
        //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
        .DADDR_IN                       (GTX1_DADDR_IN),
        .DCLK_IN                        (GTX1_DCLK_IN),
        .DEN_IN                         (GTX1_DEN_IN),
        .DI_IN                          (GTX1_DI_IN),
        .DRDY_OUT                       (GTX1_DRDY_OUT),
        .DRPDO_OUT                      (GTX1_DRPDO_OUT),
        .DWE_IN                         (GTX1_DWE_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX1_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX1_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX1_TXOUTCLK_OUT),        
        .TXRESET_IN                     (GTX1_TXRESET_IN),
        .TXUSRCLK2_IN                   (GTX1_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX1_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX1_TXN_OUT),
        .TXP_OUT                        (GTX1_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX1_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX1_TXPREEMPHASIS_IN),
        //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
        .TXDLYALIGNDISABLE_IN           (GTX1_TXDLYALIGNDISABLE_IN),
        .TXDLYALIGNMONITOR_OUT          (GTX1_TXDLYALIGNMONITOR_OUT),
        .TXDLYALIGNRESET_IN             (GTX1_TXDLYALIGNRESET_IN),
        .TXENPMAPHASEALIGN_IN           (GTX1_TXENPMAPHASEALIGN_IN),
        .TXPMASETPHASE_IN               (GTX1_TXPMASETPHASE_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX1_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX1_MGTREFCLKRX_IN}),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .TXPLLLKDET_OUT                 (),
        .TXRESETDONE_OUT                (GTX1_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX1_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX1_TXPRBSFORCEERR_IN),
        //--------------- Transmit Ports - TX Ports for PCI Express ----------------
        .TXELECIDLE_IN                  (GTX1_TXELECIDLE_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX2  (X0Y2)

    GTX_WRAPPER_GTX #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),

        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000000100)
    )
    gtx2_gtx_wrapper_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX2_LOOPBACK_IN),
        .RXPOWERDOWN_IN                 (GTX2_RXPOWERDOWN_IN),
        .TXPOWERDOWN_IN                 (GTX2_TXPOWERDOWN_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX2_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX2_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX2_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX2_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX2_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX2_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX2_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX2_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX2_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX2_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX2_RXENCHANSYNC_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GTX2_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX2_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GTX2_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GTX2_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX2_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX2_RXENPCOMMAALIGN_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX2_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX2_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX2_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX2_RXDATA_OUT),
        .RXRESET_IN                     (GTX2_RXRESET_IN),
        .RXUSRCLK2_IN                   (GTX2_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXCDRRESET_IN                  (GTX2_RXCDRRESET_IN),
        .RXELECIDLE_OUT                 (GTX2_RXELECIDLE_OUT),
        .RXEQMIX_IN                     (GTX2_RXEQMIX_IN),
        .RXN_IN                         (GTX2_RXN_IN),
        .RXP_IN                         (GTX2_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GTX2_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GTX2_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX2_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX2_RXCHANREALIGN_OUT),
        //------------- Receive Ports - RX Loss-of-sync State Machine --------------
        .RXLOSSOFSYNC_OUT               (GTX2_RXLOSSOFSYNC_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX2_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX2_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX2_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX2_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX2_RXRESETDONE_OUT),
        //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
        .DADDR_IN                       (GTX2_DADDR_IN),
        .DCLK_IN                        (GTX2_DCLK_IN),
        .DEN_IN                         (GTX2_DEN_IN),
        .DI_IN                          (GTX2_DI_IN),
        .DRDY_OUT                       (GTX2_DRDY_OUT),
        .DRPDO_OUT                      (GTX2_DRPDO_OUT),
        .DWE_IN                         (GTX2_DWE_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX2_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX2_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX2_TXOUTCLK_OUT),        
        .TXRESET_IN                     (GTX2_TXRESET_IN),
        .TXUSRCLK2_IN                   (GTX2_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX2_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX2_TXN_OUT),
        .TXP_OUT                        (GTX2_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX2_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX2_TXPREEMPHASIS_IN),
        //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
        .TXDLYALIGNDISABLE_IN           (GTX2_TXDLYALIGNDISABLE_IN),
        .TXDLYALIGNMONITOR_OUT          (GTX2_TXDLYALIGNMONITOR_OUT),
        .TXDLYALIGNRESET_IN             (GTX2_TXDLYALIGNRESET_IN),
        .TXENPMAPHASEALIGN_IN           (GTX2_TXENPMAPHASEALIGN_IN),
        .TXPMASETPHASE_IN               (GTX2_TXPMASETPHASE_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX2_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX2_MGTREFCLKRX_IN}),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .TXPLLLKDET_OUT                 (),
        .TXRESETDONE_OUT                (GTX2_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX2_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX2_TXPRBSFORCEERR_IN),
        //--------------- Transmit Ports - TX Ports for PCI Express ----------------
        .TXELECIDLE_IN                  (GTX2_TXELECIDLE_IN)

    );



    //_________________________________________________________________________
    //_________________________________________________________________________
    //GTX3  (X0Y3)

    GTX_WRAPPER_GTX #
    (
        // Simulation attributes
        .GTX_SIM_GTXRESET_SPEEDUP   (WRAPPER_SIM_GTXRESET_SPEEDUP),

        // Share RX PLL parameter
        .GTX_TX_CLK_SOURCE           ("RXPLL"),
        // Save power parameter
        .GTX_POWER_SAVE              (10'b0000000100)
    )
    gtx3_gtx_wrapper_i
    (
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GTX3_LOOPBACK_IN),
        .RXPOWERDOWN_IN                 (GTX3_RXPOWERDOWN_IN),
        .TXPOWERDOWN_IN                 (GTX3_TXPOWERDOWN_IN),
        //--------------------- Receive Ports - 8b10b Decoder ----------------------
        .RXCHARISCOMMA_OUT              (GTX3_RXCHARISCOMMA_OUT),
        .RXCHARISK_OUT                  (GTX3_RXCHARISK_OUT),
        .RXDISPERR_OUT                  (GTX3_RXDISPERR_OUT),
        .RXNOTINTABLE_OUT               (GTX3_RXNOTINTABLE_OUT),
        //----------------- Receive Ports - Channel Bonding Ports ------------------
        .RXCHANBONDSEQ_OUT              (GTX3_RXCHANBONDSEQ_OUT),
        .RXCHBONDI_IN                   (GTX3_RXCHBONDI_IN),
        .RXCHBONDLEVEL_IN               (GTX3_RXCHBONDLEVEL_IN),
        .RXCHBONDMASTER_IN              (GTX3_RXCHBONDMASTER_IN),
        .RXCHBONDO_OUT                  (GTX3_RXCHBONDO_OUT),
        .RXCHBONDSLAVE_IN               (GTX3_RXCHBONDSLAVE_IN),
        .RXENCHANSYNC_IN                (GTX3_RXENCHANSYNC_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GTX3_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GTX3_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GTX3_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GTX3_RXCOMMADET_OUT),
        .RXENMCOMMAALIGN_IN             (GTX3_RXENMCOMMAALIGN_IN),
        .RXENPCOMMAALIGN_IN             (GTX3_RXENPCOMMAALIGN_IN),
        //--------------------- Receive Ports - PRBS Detection ---------------------
        .PRBSCNTRESET_IN                (GTX3_PRBSCNTRESET_IN),
        .RXENPRBSTST_IN                 (GTX3_RXENPRBSTST_IN),
        .RXPRBSERR_OUT                  (GTX3_RXPRBSERR_OUT),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .RXDATA_OUT                     (GTX3_RXDATA_OUT),
        .RXRESET_IN                     (GTX3_RXRESET_IN),
        .RXUSRCLK2_IN                   (GTX3_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .RXCDRRESET_IN                  (GTX3_RXCDRRESET_IN),
        .RXELECIDLE_OUT                 (GTX3_RXELECIDLE_OUT),
        .RXEQMIX_IN                     (GTX3_RXEQMIX_IN),
        .RXN_IN                         (GTX3_RXN_IN),
        .RXP_IN                         (GTX3_RXP_IN),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GTX3_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GTX3_RXBUFSTATUS_OUT),
        .RXCHANISALIGNED_OUT            (GTX3_RXCHANISALIGNED_OUT),
        .RXCHANREALIGN_OUT              (GTX3_RXCHANREALIGN_OUT),
        //------------- Receive Ports - RX Loss-of-sync State Machine --------------
        .RXLOSSOFSYNC_OUT               (GTX3_RXLOSSOFSYNC_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .GTXRXRESET_IN                  (GTX3_GTXRXRESET_IN),
        .MGTREFCLKRX_IN                 ({tied_to_ground_i , GTX3_MGTREFCLKRX_IN}),
        .PLLRXRESET_IN                  (GTX3_PLLRXRESET_IN),
        .RXPLLLKDET_OUT                 (GTX3_RXPLLLKDET_OUT),
        .RXRESETDONE_OUT                (GTX3_RXRESETDONE_OUT),
        //----------- Shared Ports - Dynamic Reconfiguration Port (DRP) ------------
        .DADDR_IN                       (GTX3_DADDR_IN),
        .DCLK_IN                        (GTX3_DCLK_IN),
        .DEN_IN                         (GTX3_DEN_IN),
        .DI_IN                          (GTX3_DI_IN),
        .DRDY_OUT                       (GTX3_DRDY_OUT),
        .DRPDO_OUT                      (GTX3_DRPDO_OUT),
        .DWE_IN                         (GTX3_DWE_IN),
        //-------------- Transmit Ports - 8b10b Encoder Control Ports --------------
        .TXCHARISK_IN                   (GTX3_TXCHARISK_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .TXDATA_IN                      (GTX3_TXDATA_IN),
        .TXOUTCLK_OUT                   (GTX3_TXOUTCLK_OUT),
        .TXRESET_IN                     (GTX3_TXRESET_IN),
        .TXUSRCLK2_IN                   (GTX3_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .TXDIFFCTRL_IN                  (GTX3_TXDIFFCTRL_IN),
        .TXN_OUT                        (GTX3_TXN_OUT),
        .TXP_OUT                        (GTX3_TXP_OUT),
        .TXPOSTEMPHASIS_IN              (GTX3_TXPOSTEMPHASIS_IN),
        //------------- Transmit Ports - TX Driver and OOB signalling --------------
        .TXPREEMPHASIS_IN               (GTX3_TXPREEMPHASIS_IN),
        //------ Transmit Ports - TX Elastic Buffer and Phase Alignment Ports ------
        .TXDLYALIGNDISABLE_IN           (GTX3_TXDLYALIGNDISABLE_IN),
        .TXDLYALIGNMONITOR_OUT          (GTX3_TXDLYALIGNMONITOR_OUT),
        .TXDLYALIGNRESET_IN             (GTX3_TXDLYALIGNRESET_IN),
        .TXENPMAPHASEALIGN_IN           (GTX3_TXENPMAPHASEALIGN_IN),
        .TXPMASETPHASE_IN               (GTX3_TXPMASETPHASE_IN),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .GTXTXRESET_IN                  (GTX3_GTXTXRESET_IN),
        .MGTREFCLKTX_IN                 ({tied_to_ground_i , GTX3_MGTREFCLKRX_IN}),
        .PLLTXRESET_IN                  (tied_to_ground_i),
        .TXPLLLKDET_OUT                 (),
        .TXRESETDONE_OUT                (GTX3_TXRESETDONE_OUT),
        //------------------- Transmit Ports - TX PRBS Generator -------------------
        .TXENPRBSTST_IN                 (GTX3_TXENPRBSTST_IN),
        .TXPRBSFORCEERR_IN              (GTX3_TXPRBSFORCEERR_IN),
        //--------------- Transmit Ports - TX Ports for PCI Express ----------------
        .TXELECIDLE_IN                  (GTX3_TXELECIDLE_IN)



    );


endmodule


